### ISSUE TITLE
0.5.0 does not verify signature string but returns -9809 on SecKeyRawVerify 

### ISSUE THREAD

**Issue by rsaarloos** [TakeScoop/SwiftyRSA#47] opened 2016-10-28 16:00 UTC
After upgrading my project to Swift 3.0 and Xcode 8, I also update SwiftyRSA from 0.3.0 to 0.5.0. Now when verifying my signature using the public key (SecKey) I get isSuccessful returned false and a nil error. 

On closer inspection it seems that the internal verify function calls SecKeyRawVerify at some point, which returns -9809.

I'm using the following function:

``` swift
public func verifySignatureString(_ str: String, signature: String, publicKey: SecKey, digestMethod: DigestType = defaultDigest) -> VerificationResult
```

Any idea how to resolve this?

**Comment by ldiqual** [comment] 2016-10-29 21:38
@rsaarloos Thanks for opening an issue! Would you mind checking out the `master` branch with the new architecture and let me know if it fixes your issue?

```
pod 'SwiftyRSA', :git => 'git@github.com:TakeScoop/SwiftyRSA.git', :branch => 'master'
```

If it doesn't fix your issue, would you mind sending me an example of signature + public key that I could use to reproduce the problem? Thank you!

**Comment by rsaarloos** [comment] 2016-10-30 12:50
Hi,

On closer inspection it seems that there was something wrong with how my string was calculated that I was verifying. So sorry for that, when correcting this, the signature was validated correctly.

I did checkout however the `master` branch. Syntax did change a bit, but looks nice. I have once request however. Currently I'm extracting the public key from a certificate my self (using SecTrustCopyPublicKey) into a SecKey and passing it in the verify funtion. However I did not see a way in the `master` branch to pass this in the `PublicKey` initialiser. Do you think it is possible to add this functionality?

**Comment by ldiqual** [comment] 2016-10-31 16:10
@rsaarloos That's a great suggestion! Will track it here: https://github.com/TakeScoop/SwiftyRSA/issues/48. Since your original issue is resolved, I'll be closing this.

**Closed by ldiqual** 2016-10-31 16:10 UTC
