### ISSUE TITLE
Signature verification fails

### ISSUE THREAD

**Issue by Laban1** [TakeScoop/SwiftyRSA#51] opened 2017-01-06 22:48 UTC
Hello,

I have been using your library in production for the past 6 months or so, but after upgrading to Swift 3, I can no longer verify signatures for messages signed on our CentOS server.  I am using the exact same server-side script & keys to sign the messages as I did before upgrading to Swift 3.

Here is how the server keys were generated:
```
ssh-keygen -t rsa -f serverkey -N '' -b 2048
mv serverkey serverkey-priv.pem
ssh-keygen -f serverkey.pub -e -m pem > serverkey-pub.pem ; rm -f serverkey.pub

```

I sign the message like this:
`cat message | openssl dgst -sha256 -sign serverkey-priv.pem -out signature.bin`

Then I base64-encode signature.bin and send the message along with the base64-encoded signature to the iOS device where I try to verify the signature like this:
`set verificationResult = SwiftyRSA.verifySignatureString(stringToVerify, signature: signature, publicKeyPEM: serverKey, digestMethod: .SHA256)`

The problem is that **verificationResult.isSuccessful returns false**.  The error property is:

> Error Domain=com.takescoop.SwiftyRSA Code=500 "Couldn't decode PEM key data (base64)" UserInfo={NSLocalizedDescription=Couldn't decode PEM key data (base64)}

Here is the message: 
`Raw message, 1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ, very sensitive information!!`

The signature (base64-encoded hash):
`p9+ID34iW9+ff+2S25GY0fViWzdQgCwZIwFRZAPEk6/onODvmq3wa1471btGuez+0dtUZ3f2z3Mii7x0mmPcn0cZEvjFWVQrI0+woDd3/hcOkpIdYUHAQmaRVOARx5PZgHF0LosPf6aP1ePhHUmrJHwyTmfok+tjcZwtCaeJCQYaSFqTE3F6c78guMEaq83vg/zsBBceBlAhQSCZb3lhIJZqu8Y2AHyDpuCfrANURx8XkYwcxu5ark+/YGIdkNqrrkeg5X2daph+Qfefn8ikq/kL9wTnleJ9miKDKQVc5YqKhwhhv5Y6nZ86wVeS9+uv/Yz6HS7wwxbwRJJ28w28ZQ==`

Attached is a zip file with the actual message, hash and key pair used.

[message-hash-and-key.zip](https://github.com/TakeScoop/SwiftyRSA/files/691004/message-hash-and-key.zip)

Help with this would be much appreciated!

**Comment by ldiqual** [comment] 2017-01-09 19:16
@Laban1 Seems like a duplicate of https://github.com/TakeScoop/SwiftyRSA/issues/46#issuecomment-257117470 which is fixed in master. Can you give it a shot? Thanks!

**Comment by Laban1** [comment] 2017-01-09 22:55
@ldiqual Thanks for responding.  I have a question: in Swift 2 I was using `SwiftyRSA.verifySignatureString`, but in the 0.5.0 version, it looks as if I should be using a new Signature, Key and Message class instead?

I am using Carthage and the Signature.swift, etc. are not included in the download / build.  Cartfile: `github "TakeScoop/SwiftyRSA"` and Cartfile.resolved: `github "TakeScoop/SwiftyRSA" "0.5.0"`

Here is the checkout folder:
Laban$ ls -ltrh Carthage/Checkouts/SwiftyRSA/SwiftyRSA
total 112
```
-rw-r--r--  1 Laban  staff   510B Dec 20 12:19 SwiftyRSA.h
-rw-r--r--  1 Laban  staff   1.6K Dec 20 12:19 NSData+SHA.m
-rw-r--r--  1 Laban  staff   401B Dec 20 12:19 NSData+SHA.h
-rw-r--r--  1 Laban  staff   808B Dec 20 12:19 Info.plist
-rw-r--r--  1 Laban  staff   634B Dec 20 12:19 Data+SHA.swift
-rw-r--r--@ 1 Laban  staff    36K Jan  9 13:51 SwiftyRSA.swift
```

What am I missing?

Thanks!

**Comment by ldiqual** [comment] 2017-01-10 00:12
@Laban1 That's because carthage resolved your version to `0.5.0`, while you actually want `master`. Try something like:

```
github "TakeScoop/SwiftyRSA" "master"
```

Let me know if that works

**Comment by Laban1** [comment] 2017-01-10 19:04
@Idiqual Thanks for your suggestion - that brings down the new files.

However, the signature verification still fails (isSuccessful below is false).

I am obviously doing something wrong, but I have not been able to spot it.  Here is what I am doing:
```
do {
	let signature = try SwiftyRSA.Signature(base64Encoded: base64Signature)
	let clearMessage = try SwiftyRSA.ClearMessage(string: stringToVerify, using: .utf8)
	let publicKey = try SwiftyRSA.PublicKey(pemEncoded: serverKey)
	let result = try clearMessage.verify(with: publicKey, signature: signature, digestType: .sha256)
	if result.isSuccessful {
		return true
	}
	Log.error?.message("Signature verification failed! StringToVerify: \(stringToVerify), Signature: \(signature), ServerKey: \(serverKey)")
} catch let error as NSError {
	Log.error?.message("Error encrypting string: \(error.localizedDescription)")
}
```

The way I was doing it in the old 0.3 version (Swift 2), which was working was:
`set verificationResult = SwiftyRSA.verifySignatureString(stringToVerify, signature: signature, publicKeyPEM: serverKey, digestMethod: .SHA256)
`

As long as I can get the new (Swift 3) version of the code to do exactly what the old (Swift 2) version of the code was doing, it should all work fine again.  

Can you see what I am missing?

Thanks!

**Comment by Laban1** [comment] 2017-01-16 19:07
@Idiqual I am under a bit of pressure to get this working again (and I would prefer not to revert back to Swift 2 and SwiftyRSA 0.3).  

All I am trying to do is to sign a message on a Linux server and verify it on the iOS device.  If the above is not the correct way of doing this, could you provide a simple working example of signing a message on a Linux machine and verifying it using SwiftyRSA?  

This is not my area of expertise and I am probably just missing something stupid.  Your help would be much appreciated!

**Comment by ldiqual** [comment] 2017-01-17 18:08
@Laban1 Sorry for the delay on this. A couple questions:

 - Are you getting into the `catch` block in your last code? If yes, what does the error say? If not (which would mean you do get a result for the verification) then the only thing that comes to mind is the digest type you're using (sha256) though it seems to match.
 - Can you paste an example of private/public key as well as the clear message + signature, and the linux commands you used to generate all this? It'll help me investigate.

Let me know

**Comment by Laban1** [comment] 2017-01-17 21:58
@ldiqual

No, it does not throw an exception - it just returns isSuccessful == false.  

Re. the exact commands on the Linux-side, they are all in the original post.  Attached to that post there is also a zip file containing these files:
serverkey-priv.pem
serverkey-pub.pem
message.txt (clear message)
signature.bin (the binary signature of message)

I also attached a simple perl script to this post that I use to generate the signature (using openssl), in case it is of any use.  It is just a helper script that generates a file with the clear message followed by the signature (pipe-delimited).  E.g.: 
`Raw message, 1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ, very sensitive information!!|p9+ID34iW9+ff+2S25GY0fViWzdQgCwZIwFRZAPEk6/onODvmq3wa1471btGuez+0dtUZ3f2z3Mii7x0mmPcn0cZEvjFWVQrI0+woDd3/hcOkpIdYUHAQmaRVOARx5PZgHF0LosPf6aP1ePhHUmrJHwyTmfok+tjcZwtCaeJCQYaSFqTE3F6c78guMEaq83vg/zsBBceBlAhQSCZb3lhIJZqu8Y2AHyDpuCfrANURx8XkYwcxu5ark+/YGIdkNqrrkeg5X2daph+Qfefn8ikq/kL9wTnleJ9miKDKQVc5YqKhwhhv5Y6nZ86wVeS9+uv/Yz6HS7wwxbwRJJ28w28ZQ==`

The above is what I send to the iOS device where I split on the pipe and then verify the signature against the message.

[sigtst.zip](https://github.com/TakeScoop/SwiftyRSA/files/712385/sigtst.zip)

Please let me know if you need anything else.

Thanks.

**Comment by Laban1** [comment] 2017-01-24 23:32
@ldiqual Were you able to reproduce the issue with the information that I provided?

**Comment by ldiqual** [comment] 2017-02-02 01:30
@Laban1 I'm not sure what's up with the zip file that you attached, but when I extract it I only get one pl file:

```
[ldiqual@ldiqual-mbp-2 test]$ unzip ../sigtst.zip
Archive:  ../sigtst.zip
  inflating: sigtst.pl
```

Would you mind including the keys + text + signature? Thanks!

**Comment by ldiqual** [comment] 2017-02-02 01:31
And sorry for the delay, things got crazy here at Scoop with the Parse shutdown. Back on track!

**Comment by Laban1** [comment] 2017-02-02 01:38
@ldiqual,

The keys, etc. are in the ORIGINAL post in this thread.  Here is the link:
https://github.com/TakeScoop/SwiftyRSA/files/691004/message-hash-and-key.zip

Thanks.

**Comment by ldiqual** [comment] 2017-02-02 02:37
@Laban1 Got it, thanks! I've spent about an hour trying to figure out what's happening. I can reproduce the validation failure with all digest modes available, so they're definitely something wrong here.

However the one thing that I'm having trouble with is your public key.

I can generate a signature fine:

```
$ openssl dgst -sha256 -sign serverkey-priv.pem -out signature.bin message.txt
```

But I can't verify the message because openssl is unable to read your public key:

```
$ openssl dgst -sha256 -verify serverkey-pub.pem -keyform PEM -signature signature.bin message.txt
unable to load key file
```

I'm even unable to convert it to DER:

```
$ openssl rsa -pubin -inform PEM -in serverkey-pub.pem -outform DER -out test.der
unable to load Public Key
82333:error:0906D06C:PEM routines:PEM_read_bio:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.30.2/src/crypto/pem/pem_lib.c:648:Expecting: PUBLIC KEY
```

The key looks ok, it has the right headers and it parses correct in an ASN.1 decoder: https://lapo.it/asn1js/#3082010A0282010100D5C6F764EBA4B0CEB86177511FF88F7C5E30830357AA217111A2782401538281B682CEFD5BBADAA235A7122703D74E3393943B3846D164C9CC0C22671EAB1967A3F08A0ABF9D33B8A55DBC36F97EA86731FFC9E765B7A4381D2B3FFBC0673D89C97E18BE6428B660EBDF4C9A2BDF63454D1EA0119C82516E959197F84A7284B0648552B7A74608EB023E2DF501FA79663CB77BF5EA25C2E6FCEDD2AAB42DB86566C898B358CCF221483E676D37F70B92B2374A67818C9C1E58067958B9C804AA43C4F65F3309B4EBA170355F55D350C0E00E92C40AF91DE1EE5E8785DE55AA550CCC74F87BC881183F55C9FEBB1ED8157BF30976087386164A82FCE7849E63570203010001

I'm not too sure what prevents openssl from opening the file. Any idea?

**Comment by Laban1** [comment] 2017-02-02 17:20
@ldiqual Re. verifying the signature on CentOS, please see if this answers your question:
http://serverfault.com/questions/825392/unable-to-verify-signature-openssl

Thanks.

**Comment by Laban1** [comment] 2017-02-07 19:57
@ldiqual Did the posts above answer the question?  

Also, remember that the signature verification was working perfectly with OpenSSL-signed messages with SwiftyRSA 0.3 (Swift 2) - perhaps this can provide a clue to what the problem might be?

**Comment by Laban1** [comment] 2017-02-21 19:59
@ldiqual Bump.  Any progress at all on this?

**Comment by ldiqual** [comment] 2017-02-23 09:31
@Laban1 I gave it another shot tonight for about 2 hours and I really can't find where the issue lays in. I've tried a bunch of stuff:
 - Since your message is in ascii, load it from file with the `.ascii` encoding and create a ClearMessage with that same encoding. Didn't work. Tried a combination of `.ascii/.utf8` for both constructors to no avail.
 - Tried to see whether somehow the signature was applied on a non-hashed message (no digest as opposed to sha256 in your command). Didn't work.
 - Looked at the SwiftyRSA 0.3 code (as you said it worked under that version) and the verification code is the same: https://github.com/TakeScoop/SwiftyRSA/blob/bba2d9b2e8847d3eb916375e4aaf0d502fc1fec7/SwiftyRSA/SwiftyRSA.swift#L422-L438 and https://github.com/TakeScoop/SwiftyRSA/blob/master/SwiftyRSA/Message.swift#L242-L257. Also removed the `MemoryLayout` thingy which doesn't bring any value (we're still dividing by 1).

I'm really out of options at this point, I have no clue what's happening. @paulw11 You have really good insight on this kind of stuff, do you have any other ideas we could try?

SwiftyRSA 0.3 only supported sha1 digests, maybe we should try to sign a sha1 digest and run a verification in the latest master? @Laban1 do you have signatures that used to work with 0.3 on hand? That'd be super helpful.

**Comment by Laban1** [comment] 2017-02-23 20:34
@ldiqual  This is a strange one.  I gave up shortly after my last post (I just had to get the app to build again one way or another) and reverted back to El Capitan and Swift 2.3 (using a CCC backup taken before the upgrade to Sierra, etc.).  However, I ran into an issue getting this working (app would not build at all due to another 3rd party library not building with Swift 2 anymore [even an older version]).   So I went back to Sierra and Swift 3 again and now the signature verification worked!  I have absolutely no idea why it was not working before and what made it work now - nothing changed with the signature generation.

So the app is finally building and running fine with Swift 3!!

Thanks for your help and hard work trying to resolve this!

**Comment by ldiqual** [comment] 2017-02-24 06:51
@Laban1 Awesome! Glad it finally worked for you. I'm kind of bummed that we couldn't find the root cause of all this, but hey, at least I can click the Close button and not feel too bad. Thanks for dealing with the delays during the investigation, things are crazy over here and I haven't had much time to spend on our third party libraries recently. Have a great day!

**Closed by ldiqual** 2017-02-24 06:51 UTC
